# Site settings
title: Sunset Spark
email: hello@sunsetspark.org
description: >
  Sunset Spark is a noloco hackerspace for immigrant families in Brooklyn, NY.
  We help new Americans of all ages use science and technology for fun,
  family, and the future.
baseurl: ""
url: "https://sunsetspark.org"

# Build settings
timezone: America/New_York
future: true
highlighter: rouge
markdown: kramdown

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false
    parse_block_html: false

sass:
    style: :compressed
